
spring:
    datasource:
        url: jdbc:h2:mem:config;DB_CLOSE_DELAY=-1
        username: config
        password:
    h2:
      console:
        enabled: true
    output:
      ansi:
        enabled: always
#logging:
#  level:
#    ROOT: debug